---
title: "Demographics_EDA"
author: "Timothy Stubblefield"
date: "9/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=8)
```


# Load in packages and data
```{r}
## Acquire demographic data on tennis players

library(tidyverse)
library(stringr)
library(plotly)
library(scales)

demographics <- read.csv("https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_players.csv")

```

# clean up some variable names
```{r}
demographics <- demographics %>%
  rename(Country = ioc, Player_Id = player_id, First_Name = name_first,
         Last_Name = name_last, DOB = dob, Height = height, Wikidata_Id = wikidata_id)
```



# Plot country demographics of ATP mens players
```{r}

country_plot <- demographics %>% 
  count(Country) %>%
  mutate(Prop = n/sum(n),
         Percentage = round(Prop*100,2)) %>%
  ggplot(aes(x = Country, y = Percentage, fill = Country)) + 
  geom_bar(stat = "identity") +
  coord_cartesian(clip = "off") +
 # scale_y_continuous(labels = percent_format()) +
  theme(axis.text.x = element_blank(),
        axis.title = element_blank()
  ) +
  ggtitle("Country breakdown of Players via Country affiliation") +
  labs(x = "Country", y = "Percentage")

ggplotly(country_plot)
  
```



# Notes about the variables
\paragraph{} Height is in centimeters (cm). 
